export const TriggerError = () => {
    throw new Error('demonstrating an error caught by an Error Boundary')
}

export default TriggerError
